In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv('./data/house_test.csv')
data

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

In [3]:
data3 = data.copy()

In [4]:
data = pd.get_dummies(data)
data

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1461,20,80.0,11622,5,6,1961,1961,0.0,468.0,...,False,False,False,True,False,False,False,False,True,False
1,1462,20,81.0,14267,6,6,1958,1958,108.0,923.0,...,False,False,False,True,False,False,False,False,True,False
2,1463,60,74.0,13830,5,5,1997,1998,0.0,791.0,...,False,False,False,True,False,False,False,False,True,False
3,1464,60,78.0,9978,6,6,1998,1998,20.0,602.0,...,False,False,False,True,False,False,False,False,True,False
4,1465,120,43.0,5005,8,5,1992,1992,0.0,263.0,...,False,False,False,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,21.0,1936,4,7,1970,1970,0.0,0.0,...,False,False,False,True,False,False,False,False,True,False
1455,2916,160,21.0,1894,4,5,1970,1970,0.0,252.0,...,False,False,False,True,True,False,False,False,False,False
1456,2917,20,160.0,20000,5,7,1960,1996,0.0,1224.0,...,False,False,False,True,True,False,False,False,False,False
1457,2918,85,62.0,10441,5,5,1992,1992,0.0,337.0,...,False,False,False,True,False,False,False,False,True,False
1458,2919,60,74.0,9627,7,5,1993,1994,94.0,758.0,...,False,False,False,True,False,False,False,False,True,False

In [5]:
data = data[['OverallQual', 'GrLivArea', 'GarageCars', 'YearBuilt', 'FullBath',
       'TotalBsmtSF', '1stFlrSF', 'ExterQual_Gd', 'YearRemodAdd', 'Fireplaces',
       'KitchenQual_TA', 'GarageFinish_Unf', 'ExterQual_TA']]

# joblib으로 저장한 scaler, model 불러오기

In [6]:
import joblib

In [7]:
rs = joblib.load("./model/iowa_robustscaler.joblib")
data_scaled = rs.transform(data)
data_scaled = pd.DataFrame(data_scaled, columns=data.columns)
data_scaled

,OverallQual,GrLivArea,GarageCars,YearBuilt,FullBath,TotalBsmtSF,1stFlrSF,ExterQual_Gd,YearRemodAdd,Fireplaces,KitchenQual_TA,GarageFinish_Unf,ExterQual_TA
0,-0.5,-0.877559,-1.0,-0.260870,-1.0,-0.217910,-0.375061,0.0,-0.891892,-1.0,0.0,1.0,0.0
1,0.0,-0.208575,-1.0,-0.326087,-1.0,0.671642,0.475209,0.0,-0.972973,-1.0,-1.0,1.0,0.0
2,-0.5,0.254925,0.0,0.521739,0.0,-0.126368,-0.312224,0.0,0.108108,0.0,0.0,0.0,0.0
3,0.0,0.216300,0.0,0.543478,0.0,-0.130348,-0.316151,0.0,0.108108,0.0,-1.0,0.0,0.0
4,1.0,-0.284280,0.0,0.413043,0.0,0.574129,0.378989,1.0,-0.054054,-1.0,-1.0,0.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,-1.0,-0.574739,-2.0,-0.065217,-1.0,-0.886567,-1.062347,0.0,-0.648649,-1.0,0.0,0.0,0.0
1455,-1.0,-0.574739,-1.0,-0.065217,-1.0,-0.886567,-1.062347,0.0,-0.648649,-1.0,0.0,1.0,0.0
1456,-0.5,-0.370800,0.0,-0.282609,-1.0,0.462687,0.269023,0.0,0.054054,0.0,0.0,1.0,0.0
1457,-0.5,-0.763229,-2.0,0.413043,-1.0,-0.158209,-0.229750,0.0,-0.054054,-1.0,0.0,0.0,0.0
1458,0.5,0.828119,1.0,0.434783,0.0,0.008955,-0.178694,0.0,0.000000,0.0,0.0,0.0,0.0

In [8]:
from tensorflow.keras.models import load_model

2024-09-11 17:35:27.288342: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-09-11 17:35:29.147034: I tensorflow/c/logging.cc:34] Successfully opened dynamic library libdirectml.d6f03b303ac3c4f2eeb8ca631688c9757b361310.so
2024-09-11 17:35:29.147173: I tensorflow/c/logging.cc:34] Successfully opened dynamic library libdxcore.so
2024-09-11 17:35:29.150512: I tensorflow/c/logging.cc:34] Successfully opened dynamic library libd3d12.so
2024-09-11 17:35:29.525313: I tensorflow/c/logging.cc:34] DirectML device enumeration: found 1 compatible adapters.

In [11]:
model = load_model("./model/xgbselected_0593__1065852608.0000.keras")
pred = model.predict(data_scaled)
pred = pd.DataFrame(pred, columns=['test_pred'])
pred

2024-09-11 17:35:41.191515: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-09-11 17:35:41.194288: I tensorflow/c/logging.cc:34] DirectML: creating device on adapter 0 (AMD Radeon(TM) Graphics)
2024-09-11 17:35:41.319069: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-09-11 17:35:41.319115: W tensorflow/core/common_runtime/pluggable_device/pluggable_device_bfc_allocator.cc:28] Overriding allow_growth setting because force_memory_growth was requested by the device.
2024-09-11 17:35:41.319138: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14845 MB memory) -> physical PluggableDevice (device: 0, name: DML, pci bus id: <undefined>)

19/46 [===========>..................] - ETA: 0s

2024-09-11 17:35:41.685831: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.

46/46 [==============================] - 0s 4ms/step

2024-09-11 17:35:41.991682: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-09-11 17:35:41.991741: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14845 MB memory) -> physical PluggableDevice (device: 0, name: DML, pci bus id: <undefined>)
2024-09-11 17:35:42.011949: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-09-11 17:35:42.012028: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14845 MB memory) -> physical PluggableDevice (device: 0, name: DML, pci bus id: <undefined>)
2024-09-11 17:35:42.018003: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-09-11 17:35:42.018066: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14845 MB memory) -> physical PluggableDevice (device: 0, name: DML, pci bus id: <undefined>)

          test_pred
0     146684.343750
1     201396.984375
2     130547.070312
3     189367.250000
4     344990.718750
...             ...
1454  188754.031250
1455  114335.250000
1456  161844.734375
1457  212084.250000
1458  192787.828125

[1459 rows x 1 columns]

# 함수로 테스트 데이터 처리하기

In [12]:
def data_preporcessing(data):
    data = pd.get_dummies(data)
    data = data[['OverallQual', 'GrLivArea', 'GarageCars', 'YearBuilt', 'FullBath',
       'TotalBsmtSF', '1stFlrSF', 'ExterQual_Gd', 'YearRemodAdd', 'Fireplaces',
       'KitchenQual_TA', 'GarageFinish_Unf', 'ExterQual_TA']]
    rs = joblib.load("./model/iowa_robustscaler.joblib")
    data_scaled = rs.transform(data)
    data_scaled = pd.DataFrame(data_scaled, columns=data.columns)
    return data_scaled

In [18]:
def prediction(data):
    model = load_model("./model/xgbselected_0593__1065852608.0000.keras")
    pred = model.predict(data)
    pred = pd.DataFrame(pred, columns=['test_pred'])
    return pred

In [19]:
data2 = pd.read_csv("./data/house_test.csv")
result = data_preporcessing(data2)
result

,OverallQual,GrLivArea,GarageCars,YearBuilt,FullBath,TotalBsmtSF,1stFlrSF,ExterQual_Gd,YearRemodAdd,Fireplaces,KitchenQual_TA,GarageFinish_Unf,ExterQual_TA
0,-0.5,-0.877559,-1.0,-0.260870,-1.0,-0.217910,-0.375061,0.0,-0.891892,-1.0,0.0,1.0,0.0
1,0.0,-0.208575,-1.0,-0.326087,-1.0,0.671642,0.475209,0.0,-0.972973,-1.0,-1.0,1.0,0.0
2,-0.5,0.254925,0.0,0.521739,0.0,-0.126368,-0.312224,0.0,0.108108,0.0,0.0,0.0,0.0
3,0.0,0.216300,0.0,0.543478,0.0,-0.130348,-0.316151,0.0,0.108108,0.0,-1.0,0.0,0.0
4,1.0,-0.284280,0.0,0.413043,0.0,0.574129,0.378989,1.0,-0.054054,-1.0,-1.0,0.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,-1.0,-0.574739,-2.0,-0.065217,-1.0,-0.886567,-1.062347,0.0,-0.648649,-1.0,0.0,0.0,0.0
1455,-1.0,-0.574739,-1.0,-0.065217,-1.0,-0.886567,-1.062347,0.0,-0.648649,-1.0,0.0,1.0,0.0
1456,-0.5,-0.370800,0.0,-0.282609,-1.0,0.462687,0.269023,0.0,0.054054,0.0,0.0,1.0,0.0
1457,-0.5,-0.763229,-2.0,0.413043,-1.0,-0.158209,-0.229750,0.0,-0.054054,-1.0,0.0,0.0,0.0
1458,0.5,0.828119,1.0,0.434783,0.0,0.008955,-0.178694,0.0,0.000000,0.0,0.0,0.0,0.0

In [20]:
prediction(result)

46/46 [==============================] - 0s 3ms/step

2024-09-11 17:36:24.249188: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.

          test_pred
0     146684.343750
1     201396.984375
2     130547.070312
3     189367.250000
4     344990.718750
...             ...
1454  188754.031250
1455  114335.250000
1456  161844.734375
1457  212084.250000
1458  192787.828125

[1459 rows x 1 columns]

# XGBR 모델 불러와서 분석하기

In [21]:
data3 = pd.read_csv("./data/house_test.csv")

In [22]:
data3.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition'],
      dtype='object')

In [23]:
data3 = data3[['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrArea', 'ExterQual',
       'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure',
       'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF',
       'TotalBsmtSF', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical',
       '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath',
       'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr',
       'KitchenQual', 'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal',
       'MoSold', 'YrSold', 'SaleType', 'SaleCondition']]

In [4]:
from tensorflow.keras.models import load_model

In [5]:
model = load_model("./model/xgbselected_0593__1065852608.0000.keras")

2024-09-11 15:07:12.575042: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-09-11 15:07:12.576336: I tensorflow/c/logging.cc:34] DirectML: creating device on adapter 0 (AMD Radeon(TM) Graphics)
2024-09-11 15:07:12.982771: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-09-11 15:07:12.982819: W tensorflow/core/common_runtime/pluggable_device/pluggable_device_bfc_allocator.cc:28] Overriding allow_growth setting because force_memory_growth was requested by the device.
2024-09-11 15:07:12.982844: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14845 MB memory) -> physical PluggableDevice (device: 0, name: DML, pci bus id: <undefined>)

In [ ]:
model.predict(data)